sudo: required
dist: trusty

os: linux

addons:
  apt:
    packages:
    - cpanminus
    - nginx

language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

env:
  global:
    - JOBS=3

script:
  - perl Makefile.PL
  - make -j$(JOBS)
  - make test
  - rm -rf t/archive t/servroot
  - TEST_NGINX_ARCHIVE_PATH=t/servroot TEST_NGINX_SERVROOT=$(pwd)/t/archive prove -lv t/0-archive.t t/archive.t
